INSERT INTO produits (dci, dosage, forme, reference) VALUES
('Amikacine', '500mg', 'injectable', 'Amiklin'),
('Amoxicilline', '500mg', 'gélule', 'Clamoxyl'),
('Amoxicilline', '1g', 'comprimé', 'Clamoxyl'),
('Amoxicilline', '250mg', 'comprimé dispersible', 'Clamoxyl'),
('Amoxicilline', '250mg', 'suspension buvable', 'Clamoxyl'),
('Amoxicilline+Acide Clavulanique', '500mg/62.5mg', 'sachet', 'Augmentin'),
('Amoxicilline+Acide Clavulanique', '1000mg/125mg', 'sachet', 'Augmentin'),
('Ampicilline', '1g', 'injectable', 'Totapen'),
('Azithromycine', '500mg', 'comprimé', 'Zithromax'),
('Benzathine-benzylpénicilline', '2.4mui', 'injectable', 'Extenlliline'),
('Benzathine-benzylpénicilline', '1.2mui', 'injectable', 'Extencilline'),
('Benzylpénicilline', '1mui', 'injectable', 'PéniG'),
('Céfazoline', '1g', 'injectable', 'Céfacidal'),
('Céfixime', '200mg', 'comprimé', 'Oroken'),
('Céfixime', '100mg/5ml', 'suspension buvable', 'Oroken'),
('Céfotaxime', '1g', 'injectable', 'Claforan'),
('Ceftriaxone', '1g', 'injectable', 'Rocéphine'),
('Ciprofloxacine', '250mg', 'comprimé', 'Cifran'),
('Ciprofloxacine', '200mg', 'injectable', 'Ciproxin'),
('Ciprofloxacine', '100mg', 'injectable', 'Ciproxin'),
('Ciprofloxacine', '500mg', 'injectable', 'Ciproxin'),
('Doxycycline', '100mg', 'comprimé', 'Vibra');


INSERT INTO produits (dci, dosage, forme, reference) VALUES
('Erythromycine', '500mg', 'comprimé', 'Ery'),
('Gentamicine', '80mg/2ml', 'injectable', 'Gentalline'),
('Oxacilline', '1g', 'injectable', 'Bristopen'),
('Flucloxacilline', '250mg/5ml', 'suspension buvable', 'Staphypen'),
('Flucloxacilline', '500mg', 'comprimé', 'Staphypen'),
('Flucloxacilline', '125mg/5ml', 'suspension buvable', 'Staphypen'),
('Imipénèmes', '500mg', 'injectable', NULL),
('Phénoxyméthylpénicilline', '1000000 UI', 'comprimé', 'Ospen'),
('Sulfaméthoxazole + Triméthoprime', '400mg/80mg', 'comprimé', 'Bactrim'),
('Sulfaméthoxazole + Triméthoprime', '200mg/40mg', 'suspension buvable', 'Bactrim'),
('Sulfaméthoxazole + Triméthoprime', '800mg/160mg', 'comprimé', 'Bactrim'),
('Vancomycine', '500mg', 'injectable', 'Vanco'),
('Thiamphénicol', '750mg', 'injectable', 'Thiophénicol'),
('Imipénème + Cilastatine', '500mg/500mg', 'injectable', 'Bacqure'),
('Amoxicilline + Acide Clavulanique', '100mg/12,5mg/ml', 'sirop', 'Augmentin'),
('Amoxicilline + Acide Clavulanique', '500mg/62,5mg', 'injectable', 'Augmentin'),
('Céfuroxime', '750mg', 'injectable', 'Zinnat'),
('Cyclosérine', '250mg', 'comprimé', NULL),
('Ethambutol', '400mg', 'comprimé', 'Myambutol'),
('Ethionamide', '250mg', 'comprimé', 'Trecator'),
('Isoniazide', '300mg', 'comprimé', 'Rimifon'),
('Lévofloxacine', '250mg', 'comprimé', 'Tavanic'),
('Pyrazinamide', '400mg', 'comprimé', 'Pirilène'),
('Clofazimine', '100mg', 'comprimé', 'Lampréne'),
('Rifampicine/Isoniazide/Pyrazinamide', '75/50/150mg', 'comprimé dispersible', NULL),
('Bédaquiline', '100mg', 'comprimé', NULL),
('Linézolide', '600mg', 'comprimé', 'Zyvoxid'),
('Pyridoxine', '100mg', 'comprimé', NULL),
('Delamanid', '50mg', 'comprimé dispersible', NULL),
('Dapsone', '100mg', 'comprimé', 'Disulone'),
('Rifampicine', '300mg', 'gélule', 'Rimactan'),
('Artésunate/Amodiaquine', '25mg/67,5mg', 'comprimé', 'ASAQ'),
('Artésunate/Amodiaquine', '50mg/135mg', 'comprimé', 'ASAQ'),
('Artésunate/Amodiaquine', '100mg/270mg', 'comprimé', 'ASAQ'),
('Artéméther/Luméfantrine', '20mg/120mg', 'comprimé', 'Coartem'),
('DihydroArtémisinine/Pipéraquine', '40mg/320mg', 'comprimé', 'Duocotexcin'),
('Artésunate', '30mg/ml', 'injectable', 'Artesun'),
('Artéméther', '80mg/ml', 'injectable', 'Artemedine'),
('Sulfadoxine + Pyriméthamine', '500mg/25mg', 'comprimé', 'Fansidar'),
('Quinine', '400mg', 'injectable', 'Quinimax'),
('Primaquine', '7,5mg', 'comprimé', 'Primaquine'),
('Métronidazole', '500mg', 'comprimé', 'Flagyl'),
('Métronidazole', '200mg/5ml', 'suspension buvable', 'Flagyl'),
('Amphotéricine B liposomale', '50mg', 'injectable', 'AmBisome'),
('Fluconazole', '100mg', 'comprimé', 'Triflucan'),
('Fluconazole', '50mg/5ml', 'suspension buvable', 'Triflucan'),
('Griséofulvine', '250mg', 'comprimé', 'Griséfuline'),
('Kétoconazole', '200mg', 'comprimé', 'Nizoral'),
('Albendazole', '400mg', 'comprimé', 'Zentel'),
('Mébendazole', '100mg', 'comprimé', 'Vermox'),
('Ivermectine', '3mg', 'comprimé', 'Mectizan'),
('Praziquantel', '600mg', 'comprimé', 'Biltricide'),
('Aciclovir', '200mg', 'comprimé', 'Zovirax'),
('Valaciclovir', '500mg', 'comprimé', 'Zélitrex'),
('Ténofovir', '300mg', 'comprimé', 'Viread'),
('Raltégravir', '400mg', 'comprimé', 'Isentress'),
('Dolutégravir', '50mg', 'comprimé', 'Tivicay'),
('Oxygène', NULL, 'inhalation', 'Oxygène médical'),
('Protoxyde d’azote', NULL, 'inhalation', 'Qualité médicale'),
('Isoflurane', '184.5 g/mol', 'inhalation', 'Isoflurane'),
('Sévoflurane', '2mg/ml', 'injectable', 'Sévorane'),
('Kétamine', '50mg', 'injectable', 'Kétalar'),
('Diazépam', '10mg/ml', 'injectable', 'Valium'),
('Midazolam', '5mg/ml', 'injectable', 'Hypnovel'),
('Fentanyl', '0,5mg/10mg', 'injectable', 'Fentanyl'),
('Morphine chlorhydrate', '10mg', 'injectable', 'Morphine'),
('Tramadol', '100mg/2ml', 'injectable', 'Trabar'),
('Paracétamol', '500mg', 'comprimé', 'Doliprane'),
('Paracétamol', '125mg/5ml', 'sirop', 'Doliprane');

INSERT INTO produits (dci, dosage, forme, reference) VALUES
('Paracétamol', '1g', 'injectable', 'Perfalgan'),
('Paracétamol', '0,5g', 'injectable', 'Perfalgan'),
('Prednisone', '5mg', 'comprimé', 'Cortancyl'),
('Prednisone', '20mg', 'comprimé', 'Cortancyl'),
('Buprénorphine', '0,2mg', 'comprimé perlingual', 'Temgésic'),
('Morphine chlorhydrate', '5mg', 'comprimé', 'Morphine'),
('Morphine chlorhydrate', '10mg', 'comprimé', 'Skenan'),
('Morphine chlorhydrate', '20mg', 'comprimé', 'Skenan'),
('Morphine chlorhydrate', '30mg', 'comprimé', 'Skenan'),
('Morphine chlorhydrate LP', '10mg', 'comprimé', 'Actiskenan'),
('Morphine chlorhydrate LP', '20mg', 'comprimé', 'Actiskenan'),
('Morphine chlorhydrate LP', '30mg', 'comprimé', 'Actiskenan'),
('Morphine', '10mg', 'poudre', NULL),
('Morphine chlorhydrate LP', '60mg', 'comprimé', 'Actiskenan'),
('Méthadone', '5mg', 'gélule', 'Méthadone'),
('Méthadone', '5mg', 'sirop', 'Méthadone'),
('Sufentanil', '10µg/2ml', 'injectable', 'Sufenta'),
('Cétirizine', '10mg', 'comprimé', 'Zyrtec'),
('Dexaméthasone', '4mg', 'injectable', 'Soludécadron'),
('Dexchlorphéniramine', '2mg', 'comprimé', 'Polaramine'),
('Dexchlorphéniramine', '0,01%', 'sirop', 'Polaramine'),
('Hydrocortisone', '500mg', 'injectable', 'Hydrocortisone'),
('Hydrocortisone', '100mg', 'injectable', 'Hydrocortisone'),
('Méthylprednisolone', '40mg/ml', 'injectable', 'Solumédrol'),
('Prométhazine', '50mg/ml', 'injectable', 'Phénergan'),
('Prométhazine', '25mg', 'comprimé', 'Phénergan'),
('Charbon activé', '12g/60ml', 'solution buvable', NULL),
('Charbon', '500mg', 'comprimé', 'Carbophos'),
('Disulfurame', '500mg', 'comprimé', 'Espéral'),
('Flumazénil', '0,5mg/ml', 'injectable', 'Anexate'),
('N-acétylcystéine', '5g/25ml', 'injectable', 'Fluimicil'),
('Naloxone', '0,4mg/ml', 'injectable', 'Narcan'),
('Pralidoxime', '200mg', 'injectable', 'Contrathion'),
('EDTA disodique calcique', '500mg/10mL', 'injectable', NULL),
('Déferoxamine', '500mg', 'injectable', 'Desferal'),
('Glucagon', '1mg/ml', 'injectable', 'Glucagen'),
('Sulfate de Protamine', '1000 UAH/ml', 'injectable', 'Protamine Choay'),
('Intralipide', '20%/250ml', 'injectable', NULL),
('Concentrés de complexe prothrombinique humaine', '25U/ml', 'injectable', NULL),
('Succimer', '100mg', 'capsule orale', 'Succicaptal'),
('Sulfate de magnésium', '20%', 'injectable', NULL),
('Acide valproïque', '200mg', 'comprimé', 'Dépakine'),
('Acide valproïque', '400mg/4ml', 'injectable', 'Dépakine'),
('Valproate de sodium LP', '500mg', 'injectable', 'Dépakine'),
('Valproate de sodium', '200mg/5ml', 'solution buvable', 'Dépakine'),
('Amitriptyline', '40mg/ml', 'gouttes orales', 'Laroxyl'),
('Carbamazépine', '200mg', 'comprimé', 'Tégrétol'),
('Chlorpromazine', '100mg', 'comprimé', 'Largactil'),
('Chlorpromazine', '25mg/ml', 'injectable', 'Largactil'),
('Clonazépam', '2mg', 'gouttes', 'Rivotril'),
('Clonazepam', '1mg/ml', 'injectable', 'Rivotril'),
('Clonazépam', '2mg', 'comprimé', 'Rivotril'),
('Diazepam', '10mg/2ml', 'injectable', 'Valium'),
('Diazépam', '5mg', 'comprimé', 'Valium'),
('Phénytoïne', '30mg/5ml', 'solution buvable', 'Dihydan'),
('Phénytoïne', '100mg', 'comprimé', 'Dihydan'),
('Fluphénazine', '25mg/ml', 'injectable', 'Modécate'),
('Fluphénazine', '125mg/5ml', 'injectable', 'Modécate'),
('Halopéridol', '0,50%', 'gouttes orales', 'Haldol'),
('Halopéridol', '5mg/ml', 'injectable', 'Haldol'),
('Lévomépromazine', '100mg', 'comprimé', 'Nozinan'),
('Lévomépromazine', '25mg', 'injectable', 'Nozinan'),
('Phénobarbital', '100mg', 'comprimé', 'Gardénal'),
('Phénobarbital', '200mg/ml', 'injectable', 'Gardénal'),
('Phénobarbital', '15mg/5ml', 'solution buvable', 'Gardénal'),
('Trihexyphénidyle', '0,40%', 'gouttes', 'Artane'),
('Trihexyphénidyle', '5mg', 'comprimé', 'Artane'),
('Tropatépine', '10mg/2ml', 'injectable', 'Lepticur'),
('Tropatépine', '5mg', 'comprimé', 'Lepticur'),
('Acide folique', '5mg', 'comprimé', 'Foldine'),
('Acide folique', '2mg', 'comprimé', 'Foldine'),
('Chélateurs de fer', '125mg', 'comprimé', 'Déférasirox'),
('Chélateurs de fer', '250mg', 'comprimé', 'Déférasirox'),
('Chélateurs de fer', '500mg', 'comprimé', 'Déférasirox'),
('Cyanocobalamine', '1mg', 'injectable', 'Vitamine B12');


512 Sérum anti-D   injectable     + + + IMMUNHO RO 513 Sérum antirabique   injectable     + + +   514 Sérum antitétanique   injectable     + + +   515 Sérum antilymphocytaire 25mg injectable       + +   516 Sérum antilymphocytaire 20mg injectable         +   517 Sérum antivenimeux polyvalent   injectable   + + + + INOSERP 518 vaccin anti rougeole-rubeole       + + + +   519 vaccin ROR       + + + +   520 Vaccin antiamaril   injectable   + + + +   521 Vaccin antihépatite B   injectable   + + + +   35  522 Vaccin Antiméningo A, C, Y, W135   injectable   + + + +   523 Vaccin Antiméningo W135   injectable   + + + +   524 Vaccin antipneumococcique   injectable   + + + +   525 Vaccin antipoliomyélitique   oral   + + + +   526  Vaccin antipoliomyélitique   injectable   + + + +   527 Vaccin antirabique   injectable   + + + +   528 Vaccin antitétanique   injectable   + + + +   529 Vaccin antituberculeux   injectable   + + + +   530 Vaccin Anti-papillomavirus   injectable   + + + +   531 Vaccin antirotavirus   orale   + + + +   532 Vaccin anticovid    injectable   + + + +   533 Vaccin Pentavalent   injectable   + + + +   534 Bicarbonate de sodium 14%o perfusion     + + +   535 Bicarbonate de sodium 42%o perfusion       + +   536 Chlorure de potassium 10% perfusion     + + +   537 Chlorure de sodium 9%o perfusion   + + + +   538 Chlorure de calcium   perfusion   + + + +   539 Chlorure de magnésium   perfusion   + + + +   36  540 Chlorure de sodium (irrigation vésicale 3 litres) 9%o perfusion       + + uro 3000 541 Chlorure de sodium 10% perfusion     + + +   542 Gluconate de calcium 100mg/ml injectable   + + + +   543 Glucose 5% perfusion   + + + +   544 Glucose 10% perfusion   + + + +   545 Glucose 30% perfusion       + +   546 Ringer Lactate   perfusion   + + + +   547 Mannitol 20% perfusion       + +   548 Albumine humaine 5% perfusion         +   549 Albumine humaine 20%           +   550 Aciclovir 3% pommade ophtalmique       + + Zovirax 551 Cétoxonium 0,25% collyre   + + + + Biocidan 552 Chloramphénicol + Dexaméthasone   collyre     + + + Cébédexac ol 553 Chlortétracycline ou Tétracycline 1% pommade ophtalmique + + + + + Auréomyci ne 554 Fluorescéine 1% collyre       + +   555 Gentamicine 0,30% collyre     + + + Gentalline 556 Néomycine + Polymyxine 340.000ui+1Mui collyre     + + + Cébémyxin e 557 Norfloxacine 0,30% collyre     + + + Chibroxine 558 Dexaméthasone 0,10% collyre     + + + Désocort 559 Diclofénac 0,10% collyre     + + + Voltarène 37  560 Hydrocortisone 1% collyre       + +   561 Indométacine 0,10% collyre     + + + Indocollyre 562 Oxybuprocaïne 40mg collyre     + + + Cébésine 563 Lidocaine 2% + adrénaline Inj   injectable     + + +   564 lignocaine HCL Plain 2%/ 20ml injectable     + + +   565 Amethocaine hydrochoride  0,5%/10ml injectable     + + +   566 Tétracaïne 0,005 collyre       + + Marcaïne 567 Acétazolamide 250mg comprimé       + + Diamox 568 Acétazolamide 500mg/5ml injectable       + + Diamox 569 Brinzolamide 10mg/ml collyre       + + Azopt 570 Cartéolol 15mg collyre     + + + Cartéol 571 Pilocarpine 2% collyre       + + Pilocarpine 572 Timolol 0,25% collyre       + + Timoptol 573 Latanoprost 0,50% collyre       + + Xalatan 574 Timolol 0,50% collyre       + + Timoptol 575 Atropine 1% collyre       + + Atropine 576 Atropine 0,50% collyre       + + Atropine 577 Epinéphrine 2% collyre       + + Adrénaline 578 Tropicamide + phénylephrine 5ml   0,8%+5% collyre           Mydrane 579 Visqueux en seringue pré rempli  2%       + + +   580 Gentamycine  80mg 2ml 80mg/2ml injectable     + + +   581 Dexaméthasone  8mg 2ml 8mg/2ml  injectable     + + +   38  582 Pilocarpine      0,50% collyre     + + +   583 Cyclopentolate 0,50% collyre     + + + skiacol 584 Tropicamide 5mg/ml collyre       + + Mydriaticum 585 Picloxydine 5mg collyre   + + + + Vitabact 586 Carbomère 980 (larmes artificielles) 10mg gel ophtalmique     + + + Lacrigel 587 Cromoglycate 7mg collyre     + + + Cromoptic 588 Lévocabastine 2,5mg collyre     + + + Lévophta 589 Fluorescéine 2mg collyre     + + + Fluorescein e 590 Tropicamide 50mg collyre     + + + Mydriaticum 591 Ranibizumab 10mg/ml solution pour injection intravitréenne        + + Lucentis 592 Acide ascorbique 500mg comprimé   + + + + Vit C 593 Acide ascorbique 500mg injectable   + + + + Vit C 594 Calcium gluconate 10% injectable   + + + +   595 Calcium Vit D3 500/400 UI comprimé     + + + CalC Vita 596 Cyanocobalamine 1mg/2ml injectable     + + + Vit B12 39  597 Pyridoxine 250mg/5ml injectable     + + + Vit B6 598 Rétinol 100.000ui capsules + + + + + Vit A 599 Rétinol 200.000ui capsules + + + + + Vit A 600 Eau pour préparation injectable       + + + +   601 Glimépiride 2 mg comprimé     + + + amarel 602 Glimépiride 4 mg comprimé     + + + amarel 603 Gliclazide 60 mg comprimé     + + + DIAMICRO N 604 Insuline Mixte 30% 100UI injectable     + + +  Mixtard 605 Insuline Lente 100UI injectable     + + +  Insulatard 606 Insuline Rapide 100UI injectable     + + +  Actrapid 607 Insuline analogue pour injection à action rapide   stylo prérempli jetable     + + +   608 Insuline analogue pour injection à action lente   stylo prérempli jetable     + + +   609 Insuline analogue pour injection à action mixte   stylo prérempli jetable     + + +   610 Metformine 500mg comprimé   + + + + Glucophag e 611 Metformine 850mg comprimé   + + + + Glucophag e 612 gliclazide /metformine 60/850 mg comprimé     + + + Glide-M 613 gliclazide /metformine 60/1000 mg comprimé     + + + Glide-M 614 Carbimazole 5mg comprimé       + + Néo mercazole 615 Carbimazole 20mg comprimé       + + Néo mercazole 616 Cortisone 5mg comprimé       + + Cortisone 617 Cyprotérone 50mg comprimé       + + Androcur 618 Progesterone 200 mg ovule     + + +   619 Bicalutamide 50mg comprimé        +  + Casodex 620 hydrocortisone 10 mg comprimé        +  +   621 Goséréline            3,6 mg injectable        +  + Zoladex 622 Lévothyroxine 50µg comprimé       + + l-thyroxine 623 Lévothyroxine 100µg comprimé       + + l-thyroxine 624 Cabergoline 0,5 mg comprimé       + + DOSTINEX 625 Bléomycine 15mg injectable       + + Bléomycine 626 Carboplatine 450mg injectable        + +    627 Carboplatine 150mg injectable        + +    628 Chlormétine 10mg injectable         + Caryolysine 629 Cisplatine 10mg injectable       + + Cisplatyl 630 Cisplatine 25mg injectable       + + Cisplatyl 631 Cisplatine 50mg injectable       + + Cisplatyl 632 Cyclophosphamide 500mg injectable         + Endoxan 633 Cyclophosphamide 25mg comprimé       + +   634 Cyclophosphamide 50 mg comprimé       + +   635 Doxorubicine 10mg ;50mg injectable       + + Adriblastin e 636 Epirubicine 20mg ; 50mg injectable       + + Farmorubic ine 637 Etoposide 100mg comprimé       + + Vépéside  638 Fluorouracil 500mg/ml injectable         + Fluracil 639 Hydroxycarbamide 500mg comprimé         + Hydréa 640 Melphalan 2mg comprimé         + Alkéran 641 Melphalan 50mg injectable         +   642 Méthotrexate 50mg/ml injectable       + + Méthotrexa te 643 Méthotrexate 20mg injectable       + +   41  644 Méthotrexate 10mg injectable       + +   645 Ledertrexate 5mg injectable       + +   646 Méthotrexate 2,5mg comprimé       + + Méthotrexate 647 Méthotrexate 20mg comprimé       + + Méthotrexa te 648 Paclitaxel 30mg injectable       + + Taxol 649 Paclitaxel 100mg injectable       + + Taxol 650 Tamoxifène 20mg comprimé       + + Nolvadex 651 Vinblastine 10mg injectable       + + Nolvadex 652 Vincristine 1mg injectable       + + Oncovin 653 Vincristine 2mg injectable       + + Oncovin 654 Bevacizumab 400mg injectable       + + avastin 655 Trastuzumab 150mg injectable       + + Herceptin 656 Rituximab 100mg injectable       + + mabthera 657 Rituximab 500mg injectable       + + mabthera 658 Capecitabine 500mg injectable       + + xéloda 659 Ibandronate 50mg injectable       + + bondronat 660 Ibandronate 6mg injectable       + + bondronat 661 Filgrastim 300µg injectable       + + neupogen 662 Acide Zolédronique       4mg perfusion       + + Zométa  663 Triptoréline           0,1 mg injectable       + + Décapeptyl 664 Folinate de calcium  50mg  injectable       + +   665 Folinate de calcium  100mg injectable       + +   666 Actinomycine D 0,5mg injectable       + +   667 Pemetrexed 100mg injectable       + +   668 Pemetrexed 500mg injectable       + +   669 Thalidomide 50mg comprimé       + +   670 Fluoro-5 uracil 250mg injectable       + +   671 Fluoro-5 uracil 500mg injectable       + +   672 Anastrozole 1mg comprimé       + +  Arimidex 673 Gemcitabine 200mg  injectable       + +   674 Gemcitabine 1000mg injectable       + +   675 Letrozole 2,5mg comprimé       + +  Femara 676 Sunitinib     12,5mg gélule        + + Sutent  42  677 Azacitidine 100mg injectable       + +   678 Mercaptopurine 50mg comprimé       + +   679 Thioguanine 40mg comprimé       + +   680 Cytarabine 100mg injectable       + +   681 Ifosfamide 1g injectable       + +   682 Ifosfamide 3g injectable       + +   683 Oxaliplatine  50mg injectable       + +   684 Oxaliplatine  100mg injectable       + +   685 Dacarbazine 500mg injectable       + +   686 Dacarbazine 200mg injectable       + +   687 Témozolomide 100mg gélule        + +   688 Irinotécan 100mg injectable       + +   689 Irinotécan 500mg injectable       + +   690 Irinotécan 40mg injectable       + +   691 Topotécan 4mg injectable       + +   692 Daunorubicine 50mg injectable       + +   693 Vinorelbine 50mg          + +   694 Vinorelbine 10mg injectable       + +   695 L Asparaginase 10.000unités injectable       + +   696 Pegfilgastrim 6mg injectable       + +   697 Mesna 1g injectable       + +   698 Fludarabine 50mg injectable       + +   699 Busulphan 60mg injectable       + +   700 Chorambucil 2mg comprimé       + +   701 Oxaliplatine  100mg injectable       + +   702 Bendamustine 2,5mg injectable       + +   703 Carmustine 100mg injectable       + +   704 Procarbazine 50mg gélule        + +   705 Docetaxel 80mg         + +   706 Docetaxel 160mg injectable       + +   707 Bortézomib 3,5mg injectable       + +   708 Idarubicine 5mg injectable       + +   709 Brentuximab vedotin 50mg injectable       + +   710 Daratumumab 20mg injectable       + +   43  711 Lénalidomide 25mg gélule        + +   712 Ciclosporine 50mg comprimé       + +   713 Trétinoïne 10mg gélule        + +   714 Arsénic trrioxyde 10mg injectable       + +   715 Atézolizumab 1200mg injectable       + +   716 Pembrolizumab 50mg injectable       + +   717 Pembrolizumab 100mg injectable       + +   718 Erlotinib 150mg injectable       + +   719 Chloraminophène 2mg comprimé       + + 720 Acides aminés essentiels   perfusion     + + + Trophysan  721 Acides gras essentiels   perfusion         +   722 Complexe vitaminique   perfusion     + + +    723 Mélange ternaire (protide, glucide, lipide)   perfusion       + +   724 Oligo-éléments   perfusion         +   725 ASPE     + +       Plumpy sup 726 ATPE       + + + + plumpy nut 727 F100         + + +   728 F75       + + + +   729 Fénoxazoline 15mg/flacon goutte auriculaire       + +   730 Phénazone + Lidocaïne (4g/1g)/100g goutte auriculaire     + + + Otipax 44  731 Xylométazoline    0,5%o goutte nasale     + + + Otrivine